---
name: rebuild_org

on:
  repository_dispatch:
    types: [run_tmate]
  schedule:
    - cron: "0 * * * *"

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  RUN_TMATE: ${{ secrets.RUN_TMATE }}

jobs:
  dispatch_rebuilds:
    runs-on: ubuntu-latest
    steps:
      - name: debug_info
        uses: hmarr/debug-action@v1
      - name: check_org_repos
        uses: cisagov/action-apb@develop
        with:
          access_token: ${{ env.ACCESS_TOKEN }}
          build_age: "7d"
          event_type: "apb"
          max_rebuilds: 10
          repo_query: "org:cisagov archived:false"
          workflow_id: "build.yml"
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v2
        if: env.RUN_TMATE
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output.json
          path: output.json
