---
name: rebuild_org

on:
  schedule:
    - cron: "0 * * * *"

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  dispatch_rebuilds:
    runs-on: ubuntu-latest
    steps:
      - uses: cisagov/action-apb@develop
        with:
          access_token: ${{ env.ACCESS_TOKEN }}
          build_age: "7d"
          event_type: "apb"
          max_rebuilds: 10
          repo_query: "org:cisagov archived:false"
          workflow_id: "build.yml"
