---
name: rebuild_org

on:
  repository_dispatch:
    types: [run_tmate, run]
  schedule:
    - cron: "0 * * * *"

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  dispatch_rebuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Check all organization repositories
        uses: cisagov/action-apb@develop
        with:
          access_token: ${{ env.ACCESS_TOKEN }}
          build_age: "7d"
          event_type: "apb"
          max_rebuilds: 10
          repo_query: "org:cisagov archived:false"
          workflow_id: "build.yml"
      - name: Save apb output as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: output.json
          path: output.json
      - name: Update wiki
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository }}.wiki"
          token: ${{ env.ACCESS_TOKEN }}
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v2
        if: github.event_name == 'repository_dispatch' &&
            github.event.action == 'run_tmate'
        # uses: cisagov/action-badgeboard
        # with:
        #   page: actions
